site:
  title: GraphQL ATG
  start_page: atg::index.adoc
  url: http://localhost:3000

content:
  sources:
    - url: .
      start_path: docs/content

ui:
  bundle:
    url: ./docs/ui
  supplemental_files:
    - path: img/logo.png
      contents: ./logo/logo.png

antora:
  extensions:
    - require: '@antora/lunr-extension'
