# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'test-node-16':
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          paths:
            - .yarn/cache
            - .yarn/unplugged
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
  'test-node-latest':
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          paths:
            - .yarn/cache
            - .yarn/unplugged
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
  'build':
    docker:
      - image: circleci/node:16
    steps:
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn build
      - save_cache:
          paths:
            - build
          key: yarn-build
  'deploy':
    docker:
      - image: circleci/node:16
    type: approval
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-build
      - run: yarn publish --non-interactive

workflows:
  version: 2
  build:
    jobs:
      - 'test-node-16'
      - 'test-node-latest'
      - 'build'
      - 'deploy-approval':
          type: approval
          requires:
            - 'test-node-16'
            - 'test-node-latest'
            - 'build'
          filters:
            branches:
              only: main
      - 'deploy':
          requires:
            - 'deploy-approval'
