# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-16':
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          paths:
            - .yarn/cache
            - .yarn/unplugged
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn cov
  'node-latest':
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          paths:
            - .yarn/cache
            - .yarn/unplugged
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn cov
  'deploy':
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn publish --non-interactive

workflows:
  version: 2
  build:
    jobs:
      - 'node-16'
      - 'node-latest'
      - 'deploy':
        type: approval
        requires:
          - 'node-16'
          - 'node-latest'
